/**
 * Shell completion for Solid CLI — generated dynamically from the live
 * commander tree, so completions never drift from the registered commands.
 *
 * solid completion              → zsh (default)
 * solid completion --bash       → bash
 * solid completion --fish       → fish
 *
 * Install: eval "$(solid completion)" in ~/.zshrc (or pipe to a file sourced
 * by your shell — see the generated header comment).
 */

import { Command } from 'commander';

type Node = { name: string; aliases: string[]; desc: string; subs: Node[] };

function walk(cmd: Command): Node {
  // commander stashes aliases on `_aliases`; `.aliases()` is the public read.
  const aliases = typeof (cmd as unknown as { aliases?: () => string[] }).aliases === 'function'
    ? (cmd as unknown as { aliases: () => string[] }).aliases()
    : [];
  return {
    name: cmd.name(),
    aliases,
    desc: (cmd.description() || '').replace(/'/g, "\\'").split('\n')[0].slice(0, 80),
    subs: cmd.commands.map(walk),
  };
}

function allNames(n: Node): string[] {
  return [n.name, ...n.aliases];
}

function generateZsh(tree: Node): string {
  const tops = tree.subs;
  const commandTuples = tops
    .flatMap((t) => allNames(t).map((n) => `'${n}:${t.desc}'`))
    .join(' ');

  const subCases = tops
    .filter((t) => t.subs.length)
    .flatMap((t) => {
      const subWords = t.subs.flatMap(allNames).join(' ');
      return allNames(t).map((n) => `      ${n}) _values 'subcommand' ${subWords} ;;`);
    })
    .join('\n');

  return `#compdef solid
# Solid# CLI shell completion (zsh) — generated by \`solid completion\`
# Install: solid completion install  (or manually: eval "$(solid completion)")

# Guard: only register if compdef exists (zsh with compinit loaded). This
# prevents "command not found: compdef" when the file is sourced before
# compinit has run — a common source of startup-noise complaints.
if ! command -v compdef >/dev/null 2>&1; then
  autoload -Uz compinit 2>/dev/null
  compinit -u 2>/dev/null
fi
if ! command -v compdef >/dev/null 2>&1; then
  return
fi

_solid() {
  local -a commands
  commands=(${commandTuples})

  _arguments -C \\
    '1:command:->cmd' \\
    '*:subcommand:->sub'

  case $state in
    cmd)
      _describe 'solid command' commands
      ;;
    sub)
      case $words[2] in
${subCases}
      esac
      ;;
  esac
}

compdef _solid solid
`;
}

function generateBash(tree: Node): string {
  const tops = tree.subs;
  const cmdList = tops.flatMap(allNames).join(' ');

  const subCases = tops
    .filter((t) => t.subs.length)
    .flatMap((t) => {
      const subWords = t.subs.flatMap(allNames).join(' ');
      return allNames(t).map((n) => `    ${n}) COMPREPLY=($(compgen -W "${subWords}" -- "$cur")) ;;`);
    })
    .join('\n');

  return `# Solid# CLI bash completion — generated by \`solid completion --bash\`
# Install: solid completion --bash > ~/.solid-completion.bash && echo 'source ~/.solid-completion.bash' >> ~/.bashrc
_solid_completions() {
  local cur prev commands
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${cmdList}"

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi

  case "$prev" in
${subCases}
  esac
}

complete -F _solid_completions solid
`;
}

function generateFish(tree: Node): string {
  const lines: string[] = [];
  for (const t of tree.subs) {
    for (const n of allNames(t)) {
      lines.push(`complete -c solid -n '__fish_use_subcommand' -a '${n}' -d '${t.desc}'`);
    }
  }
  for (const t of tree.subs) {
    const anyTop = allNames(t).join(' ');
    for (const s of t.subs) {
      for (const sn of allNames(s)) {
        lines.push(`complete -c solid -n '__fish_seen_subcommand_from ${anyTop}' -a '${sn}' -d '${s.desc}'`);
      }
    }
  }
  return `# Solid# CLI fish completion — generated by \`solid completion --fish\`
# Install: solid completion --fish > ~/.config/fish/completions/solid.fish
${lines.join('\n')}
`;
}

/**
 * Detect the current shell and return (shell, rcFile, completionFile).
 * Purely based on $SHELL — we don't peek at $0 since subshells lie.
 */
function detectShell(): { shell: 'zsh' | 'bash' | 'fish'; rcFile: string; completionFile: string } {
  const os = require('os') as typeof import('os');
  const path = require('path') as typeof import('path');
  const shell = (process.env.SHELL || '').toLowerCase();
  const home = os.homedir();
  if (shell.includes('fish')) {
    return {
      shell: 'fish',
      // fish auto-loads completions from here; no rc-file edit needed.
      rcFile: '',
      completionFile: path.join(home, '.config', 'fish', 'completions', 'solid.fish'),
    };
  }
  if (shell.includes('bash')) {
    return {
      shell: 'bash',
      rcFile: path.join(home, '.bashrc'),
      completionFile: path.join(home, '.solid-completion.bash'),
    };
  }
  // zsh is the macOS default since Catalina — treat as fallback.
  return {
    shell: 'zsh',
    rcFile: path.join(home, '.zshrc'),
    completionFile: path.join(home, '.solid-completion.zsh'),
  };
}

// Sentinel line so repeat installs stay idempotent. We search for this exact
// string in the rc file; if present, we skip the append.
const SENTINEL = '# >>> solid-cli completion >>>';
const SENTINEL_END = '# <<< solid-cli completion <<<';

async function installCompletion(root: Command): Promise<{
  shell: string;
  wroteCompletion: string;
  updatedRc: string | null;
  already: boolean;
}> {
  const fs = await import('fs');
  const { shell, rcFile, completionFile } = detectShell();
  const tree = walk(root);

  const script =
    shell === 'bash' ? generateBash(tree)
    : shell === 'fish' ? generateFish(tree)
    : generateZsh(tree);

  // Write the completion script. Always overwrite — we want it to track the
  // currently-installed CLI version. User can always re-run to refresh.
  fs.mkdirSync(require('path').dirname(completionFile), { recursive: true });
  fs.writeFileSync(completionFile, script, 'utf-8');

  // fish auto-loads from ~/.config/fish/completions — no rc edit.
  if (shell === 'fish') {
    return { shell, wroteCompletion: completionFile, updatedRc: null, already: false };
  }

  // For bash/zsh, idempotently append a `source` line to the rc file.
  const existing = fs.existsSync(rcFile) ? fs.readFileSync(rcFile, 'utf-8') : '';
  if (existing.includes(SENTINEL)) {
    return { shell, wroteCompletion: completionFile, updatedRc: rcFile, already: true };
  }
  const snippet = `\n${SENTINEL}\n[ -f "${completionFile}" ] && source "${completionFile}"\n${SENTINEL_END}\n`;
  fs.appendFileSync(rcFile, snippet, 'utf-8');
  return { shell, wroteCompletion: completionFile, updatedRc: rcFile, already: false };
}

export const completionCommand = new Command('completion')
  .description('Generate or install shell completion (reflects the live command tree)')
  .option('--bash', 'Generate bash completion to stdout')
  .option('--fish', 'Generate fish completion to stdout')
  .option('--zsh', 'Generate zsh completion to stdout (default)')
  .action(function (this: Command, options) {
    const root = (this.parent as Command) ?? this;
    const tree = walk(root);

    if (options.bash) {
      console.log(generateBash(tree));
    } else if (options.fish) {
      console.log(generateFish(tree));
    } else {
      console.log(generateZsh(tree));
    }
  });

// `solid completion install` — one-shot setup.
completionCommand
  .command('install')
  .description('Auto-install completion into your shell rc (idempotent)')
  .action(async function (this: Command) {
    // walk the grandparent (root program), since `this.parent` is
    // completionCommand itself when install is a subcommand.
    const root = ((this.parent as Command)?.parent as Command) ?? (this.parent as Command);
    const chalkMod = (await import('chalk')).default;
    try {
      const r = await installCompletion(root);
      console.log('');
      console.log(chalkMod.green(`  ✓ Installed ${r.shell} completion`));
      console.log(chalkMod.dim(`    script: ${r.wroteCompletion}`));
      if (r.updatedRc) {
        if (r.already) {
          console.log(chalkMod.dim(`    ${r.updatedRc}: already wired, skipped`));
        } else {
          console.log(chalkMod.dim(`    ${r.updatedRc}: added source line`));
        }
      }
      console.log('');
      if (r.shell === 'fish') {
        console.log(chalkMod.dim('  fish loads completions automatically — new shells will pick it up.'));
      } else {
        console.log(chalkMod.dim(`  Reload with: source ${r.updatedRc}`));
      }
      console.log('');
    } catch (e) {
      console.error(chalkMod.red(`  Install failed: ${(e as Error).message}`));
      process.exit(1);
    }
  });

// `solid completion uninstall` — the honest inverse. Idempotent.
completionCommand
  .command('uninstall')
  .description('Remove the source line from your shell rc + delete the completion script')
  .action(async () => {
    const fs = await import('fs');
    const chalkMod = (await import('chalk')).default;
    const { shell, rcFile, completionFile } = detectShell();

    if (fs.existsSync(completionFile)) fs.unlinkSync(completionFile);

    if (rcFile && fs.existsSync(rcFile)) {
      const content = fs.readFileSync(rcFile, 'utf-8');
      // Strip the sentinel block. Tolerant of trailing whitespace.
      const cleaned = content.replace(
        new RegExp(`\\n?${SENTINEL}[\\s\\S]*?${SENTINEL_END}\\n?`, 'g'),
        '',
      );
      if (cleaned !== content) {
        fs.writeFileSync(rcFile, cleaned, 'utf-8');
      }
    }
    console.log(chalkMod.green(`  ✓ Uninstalled ${shell} completion`));
  });

completionCommand.addHelpText('after', `
Examples:
  $ solid completion              # zsh script → stdout
  $ solid completion --bash       # bash script → stdout
  $ solid completion --fish       # fish script → stdout

Install (zsh):
  echo 'eval "$(solid completion)"' >> ~/.zshrc && source ~/.zshrc

Install (bash):
  solid completion --bash > ~/.solid-completion.bash
  echo 'source ~/.solid-completion.bash' >> ~/.bashrc

Install (fish):
  solid completion --fish > ~/.config/fish/completions/solid.fish
`);
