/**
 * Shell completion for Solid CLI — generated dynamically from the live
 * commander tree, so completions never drift from the registered commands.
 *
 * solid completion              → zsh (default)
 * solid completion --bash       → bash
 * solid completion --fish       → fish
 *
 * Install: eval "$(solid completion)" in ~/.zshrc (or pipe to a file sourced
 * by your shell — see the generated header comment).
 */

import { Command } from 'commander';

type Node = { name: string; aliases: string[]; desc: string; subs: Node[] };

function walk(cmd: Command): Node {
  // commander stashes aliases on `_aliases`; `.aliases()` is the public read.
  const aliases = typeof (cmd as unknown as { aliases?: () => string[] }).aliases === 'function'
    ? (cmd as unknown as { aliases: () => string[] }).aliases()
    : [];
  return {
    name: cmd.name(),
    aliases,
    desc: (cmd.description() || '').replace(/'/g, "\\'").split('\n')[0].slice(0, 80),
    subs: cmd.commands.map(walk),
  };
}

function allNames(n: Node): string[] {
  return [n.name, ...n.aliases];
}

function generateZsh(tree: Node): string {
  const tops = tree.subs;
  const commandTuples = tops
    .flatMap((t) => allNames(t).map((n) => `'${n}:${t.desc}'`))
    .join(' ');

  const subCases = tops
    .filter((t) => t.subs.length)
    .flatMap((t) => {
      const subWords = t.subs.flatMap(allNames).join(' ');
      return allNames(t).map((n) => `      ${n}) _values 'subcommand' ${subWords} ;;`);
    })
    .join('\n');

  return `#compdef solid
# Solid# CLI shell completion (zsh) — generated by \`solid completion\`
# Install: echo 'eval "$(solid completion)"' >> ~/.zshrc && source ~/.zshrc

_solid() {
  local -a commands
  commands=(${commandTuples})

  _arguments -C \\
    '1:command:->cmd' \\
    '*:subcommand:->sub'

  case $state in
    cmd)
      _describe 'solid command' commands
      ;;
    sub)
      case $words[2] in
${subCases}
      esac
      ;;
  esac
}

compdef _solid solid
`;
}

function generateBash(tree: Node): string {
  const tops = tree.subs;
  const cmdList = tops.flatMap(allNames).join(' ');

  const subCases = tops
    .filter((t) => t.subs.length)
    .flatMap((t) => {
      const subWords = t.subs.flatMap(allNames).join(' ');
      return allNames(t).map((n) => `    ${n}) COMPREPLY=($(compgen -W "${subWords}" -- "$cur")) ;;`);
    })
    .join('\n');

  return `# Solid# CLI bash completion — generated by \`solid completion --bash\`
# Install: solid completion --bash > ~/.solid-completion.bash && echo 'source ~/.solid-completion.bash' >> ~/.bashrc
_solid_completions() {
  local cur prev commands
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${cmdList}"

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi

  case "$prev" in
${subCases}
  esac
}

complete -F _solid_completions solid
`;
}

function generateFish(tree: Node): string {
  const lines: string[] = [];
  for (const t of tree.subs) {
    for (const n of allNames(t)) {
      lines.push(`complete -c solid -n '__fish_use_subcommand' -a '${n}' -d '${t.desc}'`);
    }
  }
  for (const t of tree.subs) {
    const anyTop = allNames(t).join(' ');
    for (const s of t.subs) {
      for (const sn of allNames(s)) {
        lines.push(`complete -c solid -n '__fish_seen_subcommand_from ${anyTop}' -a '${sn}' -d '${s.desc}'`);
      }
    }
  }
  return `# Solid# CLI fish completion — generated by \`solid completion --fish\`
# Install: solid completion --fish > ~/.config/fish/completions/solid.fish
${lines.join('\n')}
`;
}

export const completionCommand = new Command('completion')
  .description('Generate shell completion script (reflects live command tree)')
  .option('--bash', 'Generate bash completion')
  .option('--fish', 'Generate fish completion')
  .option('--zsh', 'Generate zsh completion (default)')
  .action(function (this: Command, options) {
    // `this.parent` is the root Commander program once completionCommand is
    // attached. Walking it captures every command currently registered — no
    // hardcoded lists, no drift.
    const root = (this.parent as Command) ?? this;
    const tree = walk(root);

    if (options.bash) {
      console.log(generateBash(tree));
    } else if (options.fish) {
      console.log(generateFish(tree));
    } else {
      console.log(generateZsh(tree));
    }
  });

completionCommand.addHelpText('after', `
Examples:
  $ solid completion              # zsh script → stdout
  $ solid completion --bash       # bash script → stdout
  $ solid completion --fish       # fish script → stdout

Install (zsh):
  echo 'eval "$(solid completion)"' >> ~/.zshrc && source ~/.zshrc

Install (bash):
  solid completion --bash > ~/.solid-completion.bash
  echo 'source ~/.solid-completion.bash' >> ~/.bashrc

Install (fish):
  solid completion --fish > ~/.config/fish/completions/solid.fish
`);
