/**
 * Shell completion for Solid CLI
 *
 * solid completion              → Output zsh completion script
 * solid completion --bash       → Output bash completion script
 * solid completion --fish       → Output fish completion script
 *
 * Install: eval "$(solid completion)" in ~/.zshrc
 */

import { Command } from 'commander';

const COMMANDS = [
  'auth', 'status', 'pull', 'push', 'diff', 'serve', 'open', 'import',
  'watch', 'sandbox', 'history', 'rollback', 'deploy', 'migrate', 'logs',
  'test', 'kb', 'pages', 'site', 'services', 'clone', 'agent', 'company',
  'switch', 'crm', 'voice', 'health', 'vibe', 'integrations', 'brand',
  'inventory', 'blog', 'flow', 'widget', 'ant', 'connect', 'llms',
  'audit', 'context', 'analytics', 'seo', 'billing', 'domains', 'train',
  'design', 'insights', 'notifications', 'schedule', 'inbox', 'export',
  'webhooks', 'support', 'reports', 'payment', 'dev', 'explore', 'docs',
  'droplet', 'accounting', 'completion', 'dashboard', 'api', 'proposal',
];

const SUBCOMMANDS: Record<string, string[]> = {
  auth: ['login', 'logout', 'status', 'token', 'config'],
  pages: ['list', 'create', 'get', 'publish', 'unpublish', 'delete', 'generate'],
  site: ['list', 'create', 'info', 'delete', 'templates', 'regenerate'],
  kb: ['list', 'add', 'search', 'delete'],
  agent: ['list', 'dashboard', 'soul', 'reflect', 'memory', 'chat', 'mission', 'telemetry', 'prompt', 'settings', 'tools'],
  company: ['list', 'create', 'info', 'switch', 'members', 'invite'],
  billing: ['status', 'usage', 'invoices', 'checkout-link', 'invoice'],
  seo: ['site-audit', 'report', 'audit', 'rank', 'citations', 'gaps'],
  blog: ['list', 'get', 'create', 'update', 'delete'],
  crm: ['contacts', 'deals', 'tasks'],
  domains: ['list', 'add', 'verify', 'remove'],
  clone: ['--list', '--preview'],
  train: ['import', 'chat', 'add', 'status'],
  brand: ['get', 'update', 'css', 'export', 'audit', 'palette'],
  webhooks: ['list', 'create', 'delete', 'listen', 'test'],
  flow: ['list', 'create', 'activate', 'pause', 'test', 'archive', 'metrics'],
  sandbox: ['fork', 'list', 'deploy', 'delete', 'diff', 'status'],
  history: ['pages', 'kb'],
  health: ['quick', 'full', 'mcp'],
  analytics: ['dashboard', 'mcp-traffic'],
  completion: ['--bash', '--fish', '--zsh'],
  dashboard: ['--revenue', '--agents'],
  api: ['list', 'docs', 'call'],
};

function generateZsh(): string {
  const cmdList = COMMANDS.join(' ');
  const subCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => `      ${cmd}) _values 'subcommand' ${subs.join(' ')} ;;`)
    .join('\n');

  return `#compdef solid
# Solid# CLI shell completion — generated by solid completion

_solid() {
  local -a commands
  commands=(${COMMANDS.map(c => `'${c}:${c} command'`).join(' ')})

  _arguments -C \\
    '1:command:->cmd' \\
    '*:subcommand:->sub'

  case $state in
    cmd)
      _describe 'solid command' commands
      ;;
    sub)
      case $words[2] in
${subCases}
      esac
      ;;
  esac
}

compdef _solid solid
`;
}

function generateBash(): string {
  const cmdList = COMMANDS.join(' ');
  const subCases = Object.entries(SUBCOMMANDS)
    .map(([cmd, subs]) => `    ${cmd}) COMPREPLY=($(compgen -W "${subs.join(' ')}" -- "$cur")) ;;`)
    .join('\n');

  return `# Solid# CLI bash completion — generated by solid completion
_solid_completions() {
  local cur prev commands
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="${cmdList}"

  if [ $COMP_CWORD -eq 1 ]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
    return
  fi

  case "$prev" in
${subCases}
  esac
}

complete -F _solid_completions solid
`;
}

function generateFish(): string {
  const lines = COMMANDS.map(c => `complete -c solid -n '__fish_use_subcommand' -a '${c}' -d '${c} command'`);
  for (const [cmd, subs] of Object.entries(SUBCOMMANDS)) {
    for (const sub of subs) {
      lines.push(`complete -c solid -n '__fish_seen_subcommand_from ${cmd}' -a '${sub}'`);
    }
  }
  return `# Solid# CLI fish completion — generated by solid completion\n${lines.join('\n')}\n`;
}

export const completionCommand = new Command('completion')
  .description('Generate shell completion script')
  .option('--bash', 'Generate bash completion')
  .option('--fish', 'Generate fish completion')
  .option('--zsh', 'Generate zsh completion (default)')
  .action((options) => {
    if (options.bash) {
      console.log(generateBash());
    } else if (options.fish) {
      console.log(generateFish());
    } else {
      console.log(generateZsh());
    }
  });
